services:
  - type: web
    name: tgsr
    runtime: node
    region: frankfurt
    plan: free
    buildCommand: |
      corepack enable
      corepack prepare pnpm@9.15.2 --activate
      pnpm install --shamefully-hoist
      pnpm run build
    startCommand: NODE_ENV=production node dist/server/index.js
