services:
  - type: web
    name: tgsr
    runtime: node
    region: frankfurt
    plan: free
    buildCommand: npm install && npm run build
    startCommand: NODE_ENV=production node dist/server/index.js
