services:
  - type: web
    name: tgsr
    runtime: node
    region: frankfurt
    plan: free
    buildCommand: |
      npm install -g pnpm@9.15.2
      pnpm install --no-frozen-lockfile
      pnpm build
    startCommand: NODE_ENV=production node dist/server/index.js
